"""empty message

Revision ID: 01845a86c7de
Revises: df7bdbb3ac02
Create Date: 2024-11-30 20:04:47.616464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '01845a86c7de'
down_revision = 'df7bdbb3ac02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack_game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.JSON(), nullable=False),
    sa.Column('dealer_hand', sa.JSON(), nullable=False),
    sa.Column('player_hand', sa.JSON(), nullable=False),
    sa.Column('player_second_hand', sa.JSON(), nullable=True),
    sa.Column('player_coins', sa.Integer(), nullable=False),
    sa.Column('current_wager', sa.Integer(), nullable=False),
    sa.Column('game_over', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('player_stood', sa.Boolean(), nullable=True),
    sa.Column('double_down', sa.Boolean(), nullable=True),
    sa.Column('split', sa.Boolean(), nullable=True),
    sa.Column('current_hand', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blackjack_game_states')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack_game_states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('deck', sqlite.JSON(), nullable=False),
    sa.Column('dealer_hand', sqlite.JSON(), nullable=False),
    sa.Column('player_hand', sqlite.JSON(), nullable=False),
    sa.Column('player_coins', sa.INTEGER(), nullable=False),
    sa.Column('current_wager', sa.INTEGER(), nullable=False),
    sa.Column('game_over', sa.BOOLEAN(), nullable=True),
    sa.Column('message', sa.VARCHAR(length=256), nullable=True),
    sa.Column('player_stood', sa.BOOLEAN(), nullable=True),
    sa.Column('double_down', sa.BOOLEAN(), nullable=True),
    sa.Column('split', sa.BOOLEAN(), nullable=True),
    sa.Column('player_second_hand', sqlite.JSON(), nullable=True),
    sa.Column('current_hand', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blackjack_game_state')
    # ### end Alembic commands ###
