"""empty message

Revision ID: 11956ff96410
Revises: db1a16abadea
Create Date: 2024-12-11 11:27:14.275147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11956ff96410'
down_revision = 'db1a16abadea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blackjack_game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck', sa.PickleType(), nullable=False),
    sa.Column('dealer_hand', sa.PickleType(), nullable=False),
    sa.Column('player_hand', sa.PickleType(), nullable=False),
    sa.Column('player_second_hand', sa.PickleType(), nullable=True),
    sa.Column('player_coins', sa.Integer(), nullable=False),
    sa.Column('current_wager', sa.Integer(), nullable=False),
    sa.Column('game_over', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('player_stood', sa.Boolean(), nullable=True),
    sa.Column('double_down', sa.Boolean(), nullable=True),
    sa.Column('split', sa.Boolean(), nullable=True),
    sa.Column('current_hand', sa.String(length=10), nullable=True),
    sa.Column('dealer_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blackjack_game_state')
    op.drop_table('users')
    # ### end Alembic commands ###
