"""Change PickleType to JSON

Revision ID: df7bdbb3ac02
Revises: 9f0c2568992d
Create Date: 2024-11-30 19:33:21.170454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7bdbb3ac02'
down_revision = '9f0c2568992d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackjack_game_states', schema=None) as batch_op:
        batch_op.alter_column('deck',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('dealer_hand',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('player_hand',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('player_second_hand',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackjack_game_states', schema=None) as batch_op:
        batch_op.alter_column('player_second_hand',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('player_hand',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=False)
        batch_op.alter_column('dealer_hand',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=False)
        batch_op.alter_column('deck',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
